### ISSUE TITLE
Podcasts

### ISSUE THREAD

**Issue by jtemporal** [compiladoras/women-teaching-tech#40]
Não seria legal adicionar também uma seção para podcasts?

**Comment by beatorizu** [comment]
eu poderia fazer esse?

**Comment by BiancaPereira** [comment]
Oii @jtemporal e @beatorizu!
Olha, eu acho a ideia bem legal sim, desde que o podcast compartilhado siga todas as regras do repositório.

Só a questão do conteúdo ser apenas em vídeo segundo as regras que vou precisar alterar.

Talvez seria bom alterar o nome do repo também, porque acredito que os podcasts e alguns canais fogem da temática "teaching tech". Alguns deles vão mais para outro tema que não é bem ensinar, mas sim discutir, comentar e etc.
