### ISSUE TITLE
[Melhoria] Sinalizar conteúdo pago

### ISSUE THREAD

**Issue by BiancaPereira** [compiladoras/women-teaching-tech#51]
Sinalizar conteúdo pago como cursos e etc com algum símbolo (exemplo: 💰) 

Adicionar legenda em algum lugar do readme para identificar o símbolo também.

**Comment by BiancaPereira** [comment]
@leticiafontoura beleza!

**Comment by leticiafontoura** [comment]
PR enviada :)
